name: Release

on:
  push:
    tags:
      - "**"

    #branches:
      #- master
      #- "branch-**"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Build the Docker image
        run: make build DOCKER_TAG=test

      - name: Try to run the Docker image
        run: |
          docker run --rm test version
          docker run --rm test agent -help

  release:
    name: Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # create new releases
      packages: write # create new package versions
      discussions: write # create new announcements

    env:
      # TODO
      images: |
        index.docker.io/multani/nomad2
        ghcr.io/multani/nomad2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Metadata
        id: meta
        run: |
          echo "nomad=$(cat nomad-version)" >> $GITHUB_OUTPUT
          echo "git=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.images }}
          build-args: |
            NOMAD_VERSION=${{ steps.meta.outputs.nomad }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          discussion_category_name: announcements
          name: Nomad ${{ steps.meta.outputs.nomad }}
          # TODO
          body: |
            [Nomad ${{ steps.meta.outputs.nomad }}](https://github.com/hashicorp/nomad/releases/tag/v${{ steps.meta.outputs.nomad }})


            Pull from [Docker Hub](https://hub.docker.com/r/multani/nomad/):

            ```
            docker pull multani/nomad2:${{ steps.meta.outputs.git }}
            ```

            or [GitHub Packages](https://github.com/multani/docker-nomad-refactor/pkgs/container/nomad):

            ```
            docker pull ghcr.io/multani/nomad2:${{ steps.meta.outputs.git }}
            ```
