name: Tag Release

on:
  push:
    paths:
      - nomad-version

jobs:
  test-and-tag:
    name: Test and Tag
    runs-on: ubuntu-latest

    permissions:
      contents: write # create new tags

    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Build the Docker image
        run: docker build --tag test .

      - name: Try to run the Docker image
        run: |
          docker run --rm test version
          docker run --rm test agent -help

      - name: Create tag
        run: ./.github/actions/create-tag.sh
