name: Test

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test-debian:
    name: Test Debian

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0

      - name: Metadata
        id: meta
        run: |
          echo "nomad=$(cat nomad-version)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        id: docker-setup
        uses: docker/setup-qemu-action@v2
        with:
          platforms: amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: local/nomad
          tags: type=raw,value=test

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |-
            NOMAD_VERSION=${{ steps.meta.outputs.nomad }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          load: true

      - name: Test
        run: make test DOCKER_TAG=${{ steps.docker-meta.outputs.tags }}

      - name: Build all platforms
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |-
            NOMAD_VERSION=${{ steps.meta.outputs.nomad }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          platforms: ${{ steps.docker-setup.outputs.platforms }}

  test-alpine:
    name: Test Alpine

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint the Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile.alpine

      - name: Metadata
        id: meta
        run: |
          echo "nomad=$(cat nomad-version)" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v4
        with:
          images: local/nomad
          tags: type=raw,value=test

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          build-args: |-
            NOMAD_VERSION=${{ steps.meta.outputs.nomad }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          load: true

      - name: Test
        run: make test DOCKER_TAG=${{ steps.docker-meta.outputs.tags }}
